auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: BeiYuu.com
url: http://alfred-sun.github.io
feed: /atom.xml
author_info: <a href="http://alfred-sun.github.io/">Alfred Sun</a>
